// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFTfAzVtXtFo24tYHuL_p9A2CqeShwFAY',
    appId: '1:401478710083:web:4a9f052639589c5fcbb5f6',
    messagingSenderId: '401478710083',
    projectId: 'reddit-clone-ad2be',
    authDomain: 'reddit-clone-ad2be.firebaseapp.com',
    storageBucket: 'reddit-clone-ad2be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs_2EPr1b4qTbUmZRdVTvkXg35ehp1D90',
    appId: '1:401478710083:android:e94af57b12f23d3fcbb5f6',
    messagingSenderId: '401478710083',
    projectId: 'reddit-clone-ad2be',
    storageBucket: 'reddit-clone-ad2be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBftw1O80NZVb7_24WYOrbhZ4hKLUXfm9A',
    appId: '1:401478710083:ios:5039e642f3feb66dcbb5f6',
    messagingSenderId: '401478710083',
    projectId: 'reddit-clone-ad2be',
    storageBucket: 'reddit-clone-ad2be.firebasestorage.app',
    iosBundleId: 'com.isyo.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBftw1O80NZVb7_24WYOrbhZ4hKLUXfm9A',
    appId: '1:401478710083:ios:5039e642f3feb66dcbb5f6',
    messagingSenderId: '401478710083',
    projectId: 'reddit-clone-ad2be',
    storageBucket: 'reddit-clone-ad2be.firebasestorage.app',
    iosBundleId: 'com.isyo.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFTfAzVtXtFo24tYHuL_p9A2CqeShwFAY',
    appId: '1:401478710083:web:c970554123d17927cbb5f6',
    messagingSenderId: '401478710083',
    projectId: 'reddit-clone-ad2be',
    authDomain: 'reddit-clone-ad2be.firebaseapp.com',
    storageBucket: 'reddit-clone-ad2be.firebasestorage.app',
  );
}
